version: '2'
services:
    gitmanager-app:
        image: gitmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gitmanager-mysql:3306/gitmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gitmanager-mysql:
        extends:
            file: mysql.yml
            service: gitmanager-mysql
